# Generated by Django 3.1.7 on 2021-03-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinplay_api', '0002_auto_20210305_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='artist',
            new_name='playlist_name',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song',
        ),
    ]
