# Generated by Django 3.1.7 on 2021-04-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinplay_api', '0003_auto_20210305_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
