# Generated by Django 3.1.7 on 2021-04-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinplay_api', '0003_auto_20210305_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifySong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('explicit', models.BooleanField()),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
