# Generated by Django 3.1.7 on 2021-04-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pinplay_api', '0004_delete_playlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('explicit', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=40)),
                ('track', models.ManyToManyField(to='pinplay_api.track')),
            ],
        ),
    ]
